/**
 * Vectorises the brand logo artwork into the SVG paths the site uses.
 *
 *   node scripts/trace-logo.mjs
 *
 * Outputs:
 *   src/generated/logo-paths.ts   — path data inlined by src/components/LogoSprite.astro
 *   public/atrio-pms-logo.svg     — full lockup, navy (og:image, external use)
 *   public/favicon.svg            — monogram, white on a navy rounded square
 *
 * Only needs re-running when the source artwork changes.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import potrace from 'potrace';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(
  here,
  '../../stitch_atrio_pms_administrative_dashboard/screen.png/screen.png',
);

const BRAND_NAVY = '#1a3668';

/**
 * Crops of the source artwork, in source pixels. The artwork's ink spans
 * x 173–850, y 395–628; the monogram ends at x 460 (the gap before "ATRIO").
 * Each region adds 4px of breathing room on every side.
 */
const REGIONS = {
  /** The "A" monogram on its own. */
  mark: { left: 169, top: 391, width: 296, height: 242 },
  /** Monogram plus the ATRIO / PMS wordmark. */
  full: { left: 169, top: 391, width: 686, height: 242 },
};

/** Renders a region to the high-contrast bitmap potrace traces. */
function toBitmap(region) {
  return sharp(SOURCE)
    .extract(region)
    .resize({ width: region.width * 3, kernel: 'lanczos3' })
    .greyscale()
    .normalise()
    .blur(0.7) // Softens resampling artefacts so potrace emits fewer segments.
    .png()
    .toBuffer();
}

/**
 * Traces a bitmap to a single path. potrace emits one <path> per shape and
 * relies on the even-odd fill rule to punch out counters (the leaf interior,
 * the "O" of ATRIO), so the merged path must be rendered with fill-rule="evenodd".
 */
function trace(buffer) {
  return new Promise((resolvePath, reject) => {
    const tracer = new potrace.Potrace({
      threshold: 170,
      turdSize: 6,
      alphaMax: 1,
      optCurve: true,
      optTolerance: 0.6,
    });
    tracer.loadImage(buffer, (error) => {
      if (error) return reject(error);
      const svg = tracer.getSVG();
      const d = [...svg.matchAll(/ d="([^"]+)"/g)].map((match) => match[1]).join(' ');
      const [, width, height] = svg.match(/viewBox="0 0 (\d+) (\d+)"/) ?? [];
      resolvePath({ d, width: Number(width), height: Number(height) });
    });
  });
}

const traced = {};
for (const [name, region] of Object.entries(REGIONS)) {
  traced[name] = await trace(await toBitmap(region));
  const { width, height, d } = traced[name];
  console.log(`${name}: ${width}x${height}, ${d.length} chars`);
}

await mkdir(resolve(here, '../src/generated'), { recursive: true });
await writeFile(
  resolve(here, '../src/generated/logo-paths.ts'),
  `// Generated by scripts/trace-logo.mjs from the brand logo artwork. Do not edit by hand.
// Render with fill-rule="evenodd" so the counters stay open.
export const logoPaths = ${JSON.stringify(traced, null, 2)} as const;

export type LogoVariant = keyof typeof logoPaths;
`,
);

// Standalone full lockup, for og:image and anywhere outside the app.
const { width: fw, height: fh, d: fd } = traced.full;
await writeFile(
  resolve(here, '../public/atrio-pms-logo.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${fw} ${fh}" role="img" aria-label="ATRIO PMS">
  <path fill="${BRAND_NAVY}" fill-rule="evenodd" d="${fd}"/>
</svg>
`,
);

// Favicon: the monogram reversed out of a navy rounded square, so it stays
// legible against both light and dark browser chrome.
const { width: mw, height: mh, d: md } = traced.mark;
const scale = 0.62;
const size = Math.max(mw, mh);
const tx = (size - mw * scale) / 2;
const ty = (size - mh * scale) / 2;
await writeFile(
  resolve(here, '../public/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" rx="${Math.round(size * 0.22)}" fill="${BRAND_NAVY}"/>
  <path fill="#ffffff" fill-rule="evenodd" transform="translate(${tx.toFixed(1)} ${ty.toFixed(1)}) scale(${scale})" d="${md}"/>
</svg>
`,
);

console.log('wrote src/generated/logo-paths.ts, public/atrio-pms-logo.svg, public/favicon.svg');
